# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-fastkafka',
                'doc_host': 'https://kumaranvpl.github.io',
                'git_url': 'https://github.com/kumaranvpl/test-fastkafka',
                'lib_path': 'test_fastkafka'},
  'syms': { 'test_fastkafka.application': { 'test_fastkafka.application.IrisInputData': ( 'application.html#irisinputdata',
                                                                                          'test_fastkafka/application.py'),
                                            'test_fastkafka.application.IrisPrediction': ( 'application.html#irisprediction',
                                                                                           'test_fastkafka/application.py'),
                                            'test_fastkafka.application.Model': ('application.html#model', 'test_fastkafka/application.py'),
                                            'test_fastkafka.application.Model.predict': ( 'application.html#model.predict',
                                                                                          'test_fastkafka/application.py'),
                                            'test_fastkafka.application.on_input_data': ( 'application.html#on_input_data',
                                                                                          'test_fastkafka/application.py'),
                                            'test_fastkafka.application.to_predictions': ( 'application.html#to_predictions',
                                                                                           'test_fastkafka/application.py')},
            'test_fastkafka.core': {'test_fastkafka.core.foo': ('core.html#foo', 'test_fastkafka/core.py')}}}
