version: "3"
services:
    fastkafka-devel:
        image: ghcr.io/airtai/nbdev-mkdocs
        hostname: $DOCKER_COMPOSE_PROJECT-devel
        container_name: $DOCKER_COMPOSE_PROJECT-devel
        ports:
            - "${PORT_PREFIX}8888:8888"
            - "${PORT_PREFIX}4000:4000"
            - "${PORT_PREFIX}6006:6006"
        networks:
            - fastkafka-network
        volumes:
            - $AIRT_PROJECT:/work/fastkafka
            - /etc/passwd:/etc/passwd
            - /etc/group:/etc/group
            - /etc/shadow:/etc/shadow
            - $HOME/.ssh:$HOME/.ssh
            - $HOME/.gitconfig:/root/.gitconfig
        environment:
            KAFKA_HOSTNAME: $KAFKA_HOSTNAME
            KAFKA_PORT: 9092
            USER: $USER
            USERNAME: $USERNAME
            PRESERVE_ENVS: $PRESERVE_ENVS
            OPENAI_API_KEY: $OPENAI_API_KEY
        depends_on:
            kafka:
                condition: service_healthy

networks:
    fastkafka-network:
        name: "${USER}-fastkafka-network"
